name: mobifone_meet_platform_interface
description: A common platform interface for the mobifone meet plugin.
version: 2.0.0
homepage: https://github.com/haonv151168/jitsi_meet

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

